# Generated by Django 3.2.8 on 2021-10-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant_api', '0002_auto_20211010_1728'),
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_first_address', models.CharField(max_length=100)),
                ('delivery_second_address', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('order_status', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_api.restaurant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant_api.food')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_api.order')),
            ],
        ),
    ]
