# Generated by Django 3.2.8 on 2021-10-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='order_detail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
