# Generated by Django 3.2.8 on 2021-10-26 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu_food',
            old_name='food',
            new_name='food_id',
        ),
        migrations.RenameField(
            model_name='menu_food',
            old_name='restaurant_menu',
            new_name='restaurant_menu_id',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.RenameField(
            model_name='ownership',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='restaurant_menu',
            old_name='menu',
            new_name='menu_id',
        ),
        migrations.RenameField(
            model_name='restaurant_menu',
            old_name='restaurant',
            new_name='restaurant_id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='food',
            name='id',
        ),
        migrations.RemoveField(
            model_name='food',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='menu_food',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='menu_food',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='id',
        ),
        migrations.RemoveField(
            model_name='ownership',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='restaurant_menu',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='restaurant_menu',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='food',
            name='timestamp_ptr',
            field=models.OneToOneField(auto_created=True, default=3, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timestamp.timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ownership',
            name='timestamp_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timestamp.timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='timestamp_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timestamp.timestamp'),
            preserve_default=False,
        ),
    ]
