# Generated by Django 3.2.8 on 2021-10-17 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0009_auto_20211017_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='active',
        ),
    ]
