# Generated by Django 3.2.8 on 2021-10-11 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0004_auto_20211011_1659'),
        ('restaurant_api', '0003_alter_ownership_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownership',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_api.user'),
        ),
    ]
