# Generated by Django 3.2.8 on 2021-10-14 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_api', '0004_alter_ownership_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurnat_name',
            new_name='restaurant_name',
        ),
        migrations.RemoveField(
            model_name='restaurant_menu',
            name='name',
        ),
        migrations.RemoveField(
            model_name='restaurant_menu',
            name='num_stars',
        ),
        migrations.RemoveField(
            model_name='restaurant_menu',
            name='release_date',
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='delivery_status',
            field=models.BooleanField(null=True),
        ),
    ]
