# Generated by Django 3.2.8 on 2021-10-26 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timestamp', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='order',
            name='timestamp_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timestamp.timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order_detail',
            name='timestamp_ptr',
            field=models.OneToOneField(auto_created=True, default=2, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='timestamp.timestamp'),
            preserve_default=False,
        ),
    ]
